// Custom Worker entrypoint (TODO 6.1).
//
// OpenNext's generated worker only exports `fetch`, but Cloudflare cron triggers
// only invoke `scheduled`. This thin wrapper reuses the generated fetch handler
// unchanged and adds a scheduled() that fires one in-process call to the cron
// route — carrying the shared CRON_SECRET — so all the real work stays inside
// the normal Next runtime (see src/app/api/cron/scheduler/route.ts). The cron
// cadence lives in wrangler.jsonc `triggers.crons`.
//
// `./.open-next/worker.js` is a build artifact (gitignored, generated by
// `opennextjs-cloudflare build`); it may be absent at type-check time and
// present at bundle time, so the imports are deliberately ignored for TS.
// @ts-ignore - generated at build time by @opennextjs/cloudflare
import { default as handler } from "./.open-next/worker.js";

// Durable Object / cache handlers must be re-exported from the custom entry, or
// the runtime can't find the bound classes.
// @ts-ignore - generated at build time by @opennextjs/cloudflare
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

// Minimal structural types so this file type-checks without pulling in
// @cloudflare/workers-types.
type CronEnv = { CRON_SECRET?: string };
type WaitUntilCtx = { waitUntil(promise: Promise<unknown>): void };

export default {
  fetch: handler.fetch,
  async scheduled(_event: unknown, env: CronEnv, ctx: WaitUntilCtx) {
    const req = new Request("https://cron.internal/api/cron/scheduler", {
      method: "POST",
      headers: { "x-cron-secret": env.CRON_SECRET ?? "" },
    });
    ctx.waitUntil(handler.fetch(req, env, ctx));
  },
};
