import type { Metadata } from "next";
import { Inter, Fraunces } from "next/font/google";
import "./globals.css";
import { SITE_URL, SITE_NAME, SITE_TAGLINE, DEFAULT_OG_IMAGE } from "@/lib/seo";

// Site-wide type: Inter for UI, Fraunces for warm display lines. Exposed as CSS
// variables so Tailwind's font-sans / font-serif resolve everywhere. The
// (storyteller) route group overrides --font-sans with Atkinson Hyperlegible for
// the elder-facing surface.
const sans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const serif = Fraunces({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-serif",
  display: "swap",
});

// metadataBase makes the relative canonical/OG URLs from lib/seo resolve to
// absolute ones. The defaults here are inherited site-wide and overridden
// per-page (marketing pages via pageMeta()).
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — ${SITE_TAGLINE}`,
    template: `%s — ${SITE_NAME}`,
  },
  description: "Capture a loved one's life stories, in their own voice.",
  // Brand favicon / PWA icons (Phase 8.9) — rasters generated by
  // scripts/gen-icons.mjs from the brand illustration into public/.
  // favicon.ico for browser tabs / legacy, apple-touch-icon for iOS home screens.
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [{ url: "/favicon.ico", sizes: "any" }],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    images: [{ url: DEFAULT_OG_IMAGE, width: 1200, height: 630, alt: SITE_NAME }],
  },
  twitter: {
    card: "summary_large_image",
    images: [DEFAULT_OG_IMAGE],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${sans.variable} ${serif.variable}`}>
      <body className="font-sans">{children}</body>
    </html>
  );
}
