// Brand raster generator (Phase 8.9 — regenerated via Creative Claw).
//
// Derives the committed favicon / PWA / Apple-touch icons from the master brand
// illustration at assets/brand/icon-master.png (an on-brand golden-hour porch
// scene generated with Creative Claw's gpt-image-2). Run with `npm run gen:icons`.
//
// sharp downscales the master to each target size; png-to-ico packs a
// multi-resolution favicon.ico (16/32/48) for legacy browsers / bookmarks.
// Both are devDependencies used ONLY by this script — never imported by app
// code, so they add zero weight to the Cloudflare Workers bundle. The generated
// PNG/ICO files are committed so production serves them as plain static assets.
//
// NOTE: the social/OG image (public/og.png) is produced separately via Creative
// Claw — an AI porch scene (assets/brand/og-scene.png) composited with the
// real Fraunces wordmark — and committed as a static artifact. It is NOT
// regenerated by this script (it needs the Creative Claw renderer + web fonts).

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import sharp from "sharp";
import pngToIco from "png-to-ico";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const master = join(root, "assets", "brand", "icon-master.png");
const out = join(root, "public");

/** Downscale the master illustration to a square PNG buffer of the given size. */
const png = (size) =>
  sharp(master).resize(size, size, { fit: "cover" }).png().toBuffer();

// Square app/PWA/Apple icons + the small sizes packed into the .ico.
const [p16, p32, p48, p180, p192, p512] = await Promise.all(
  [16, 32, 48, 180, 192, 512].map(png),
);

writeFileSync(join(out, "apple-touch-icon.png"), p180);
writeFileSync(join(out, "icon-192.png"), p192);
writeFileSync(join(out, "icon-512.png"), p512);

// Multi-resolution favicon.ico (16/32/48) for legacy browsers / bookmarks.
const ico = await pngToIco([p16, p32, p48]);
writeFileSync(join(out, "favicon.ico"), ico);

const kb = (b) => `${(b.length / 1024).toFixed(1)} KB`;
console.log("Brand icons written to public/ (from assets/brand/icon-master.png):");
console.log(`  favicon.ico          ${kb(ico)}`);
console.log(`  apple-touch-icon.png ${kb(p180)}`);
console.log(`  icon-192.png         ${kb(p192)}`);
console.log(`  icon-512.png         ${kb(p512)}`);
console.log("  og.png               (committed Creative Claw artifact — not regenerated here)");
